apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: anadepday5
  name: anadepday5
  namespace: anauska
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anadepday5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: anadepday5
    spec:
      containers:
      - image: anauskadocker1/eyappday5:v1
        name: eyappday5
        imagePullPolicy: Always
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: anadepsvc1
  name: anadepsvc1
  namespace: anauska
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: anadepday5
  type: NodePort
status:
  loadBalancer: {}
